server.port: 8080
server.ssl.enabled: false

# MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gallery
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**